### ISSUE TITLE
Improve build script

### ISSUE THREAD

**Issue by mklasby** [mklasby/pytorch-poetry-hydra-template#8]
Currently the init_proj.py script is not user friendly. 

## TODOs:
- [ ] Implement input santization and checking
- [ ] Pre populate working dir field with pathlib.Path.cwd()
- [ ] Add examples of valid inputs to prompts
- [ ] Enable blank fields where possible (e.g., `<<repo-url>>`)
- [ ] Test on macos and windows. Try copy/pasting and make sure input doesn't read any extra characters
